# Generated by Django 2.2 on 2019-10-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'ToDo lists'},
        ),
    ]
